version: '2'

services:
  mysql:
    image: mysql:5.5
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - mysql.env


  web:
    build: .
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - .:/web

volumes:
  mysql_data: