version: '2'

services:
  mysql:
    image: mysql:5.5
    env_file:
      - mysql.env
    volumes:
      - mysql_data:/var/lib/mysql


  web:
    build: .
    depends_on:
      - mysql
    env_file:
      - flask.env
    ports:
      - "8000:8000"
    volumes:
      - .:/web

volumes:
  mysql_data:
